name: Check conventional commits
description: Checks all commits on PR if they satisfy conventional commits
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: "git log $(git show-ref -s $GITHUB_BASE_REF)..$(git show-ref -s $GITHUB_REF)"
      shell: bash
